### ISSUE TITLE
Issue with initialisation of BMP280

### ISSUE THREAD

**Issue by MacSimmy** [androidthings/weatherstation#3]
Hi, 
I have Rasberry Pi 3 with BMP280 sensor. It is crashing on initializing BMP sensor.
Logs:
```
 FATAL EXCEPTION: main
                 Process: com.example.androidthings.weatherstation, PID: 1463
                                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.androidthings.weatherstation/com.example.androidthings.weatherstation.WeatherStationActivity}: java.lang.RuntimeException: Error initializing BMP280
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                         Caused by: java.lang.RuntimeException: Error initializing BMP280
                                                                                            at com.example.androidthings.weatherstation.WeatherStationActivity.onCreate(WeatherStationActivity.java:180)
                                                                                            at android.app.Activity.performCreate(Activity.java:6662)
                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                                         Caused by: com.google.android.things.pio.PioException: android.os.ServiceSpecificException: I/O error
                                                                                            at com.google.android.things.pio.I2cDevice.readRegByte(I2cDevice.java:104)
                                                                                            at com.google.android.things.contrib.driver.bmx280.Bmx280.connect(Bmx280.java:171)
                                                                                            at com.google.android.things.contrib.driver.bmx280.Bmx280.<init>(Bmx280.java:149)
                                                                                            at com.google.android.things.contrib.driver.bmx280.Bmx280SensorDriver.<init>(Bmx280SensorDriver.java:54)
                                                                                            at com.example.androidthings.weatherstation.WeatherStationActivity.onCreate(WeatherStationActivity.java:174)
                                                                                            at android.app.Activity.performCreate(Activity.java:6662) 
                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                                         Caused by: android.os.ServiceSpecificException: I/O error
                                                                                            at android.os.Parcel.readException(Parcel.java:1697)
                                                                                            at android.os.Parcel.readException(Parcel.java:1636)
                                                                                            at com.google.android.things.pio.IPeripheralManagerClient$Stub$Proxy.I2cReadRegByte(IPeripheralManagerClient.java:1431)
                                                                                            at com.google.android.things.pio.I2cDevice.readRegByte(I2cDevice.java:102)
                                                                                            at com.google.android.things.contrib.driver.bmx280.Bmx280.connect(Bmx280.java:171) 
                                                                                            at com.google.android.things.contrib.driver.bmx280.Bmx280.<init>(Bmx280.java:149) 
                                                                                            at com.google.android.things.contrib.driver.bmx280.Bmx280SensorDriver.<init>(Bmx280SensorDriver.java:54) 
                                                                                            at com.example.androidthings.weatherstation.WeatherStationActivity.onCreate(WeatherStationActivity.java:174) 
                                                                                            at android.app.Activity.performCreate(Activity.java:6662) 
                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```
I used the same wiring as said in this repo. Could you please help me out here.

**Comment by RamGude** [comment]
If you have the Rainbow hat, you don't need wiring. If you just have the sensor maybe you can start with driver-samples sample codes?

**Comment by Sdcxv** [comment]
Check this on your config.txt file:

```
# pwm and I2S are mutually-exclusive since they share hardware clocks.  To
# enable I2S comment out the pwm line and uncomment the generic-i2s line.
dtoverlay=pwm-2chan-with-clk,pin=18,func=2,pin2=13,func2=4
# dtoverlay=generic-i2s
```

I had set i2s on for the other project, it should be turn off when you need to run the weather station project.

**Comment by mangini** [comment]
@MacSimmy what breakout board are you using? I/O error can be that your wiring is malfunctioning (a bad connection or a broken jumper wire, for example). I suggest that you replace all wires and your breadboard (or whatever you're using to connect the bmp280 to the wires.

**Comment by MacSimmy** [comment]
Thanks @mangini  for the help, internally broken jumper wire was the culprit in my case. That wire was broken internally without any scratch from outside and gives me really hard time to find that.
